### ISSUE TITLE
Adding Attribute to .geojson file

### ISSUE THREAD

**Issue by Mike-Honey** [Code-for-All/geodata-scripts#1]
I just realised I missed a step in my manual process. After downloading the zipped shapefile, I open it in QGIS, filter for recent DATE (e.g. last 3 months), Export as .geojson and then add an Attribute: Location = @row_number. This adds a sequential number to each shape, which is a requirement for the Mapbox visual (to relate each shape back to the data).  

Do you know how to script that?

**Comment by milovanderlinden** [comment]
Working on it now.

**Comment by milovanderlinden** [comment]
Yes, fixed. You now have an extra attribute in the json called "ROW_NUMBER" and the first column in each CSV file also containts a ROW_NUMBER. I am checking in the code now.
